name: Deploy Packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Lerna
        run: npm install -g lerna

      - name: Add Github Token
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc

      - name: Get Git Config
        id: git-config
        run: |
          export GIT_AUTHOR_NAME=$(git config --global user.name)
          export GIT_AUTHOR_EMAIL=$(git config --global user.email)
        shell: bash

      - name: Configure Git
        run: |
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          git config --global user.name "${GIT_AUTHOR_NAME}"

      - name: Publish
        run: lerna publish --registry=https://npm.pkg.github.com/ patch --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
